[package]
name = "py_svg_hush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_svg_hush"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
svg-hush = "0.9.1"
data-url = "0.2.0"
